# File: .github/workflows/OIDC_workflow.ym
name: Run Azure Login
on: [push]

permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      
      - name: Checkout
        uses: actions/checkout@v1

      - name: Replace Tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '__'
          tokenSuffix: '__'
          files: '["**/*.sh"]'
        env:
          grupo: garridoGithubAction
          loca: westeurope
          vnetname: vnetgarrido
          nicname: nicgarrido
          nsgname: nsgarrido
          subnetname: subnetgarrido
          vmname: garrido
          image: UbuntuLTS
          

      - name: Azure CLI red virtual
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/redvirtual.sh
            $GITHUB_WORKSPACE/redvirtual.sh

      - name: Azure CLI NIC
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/nic.sh
            $GITHUB_WORKSPACE/nic.sh

      - name: Azure CLI VM
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/maqcli.sh
            $GITHUB_WORKSPACE/maqcli.sh

                

